# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03aab85264ef0801516ba75cb185714438f0f8c3fd23a2452e360438ce1ac6559559e52e05a3833208cfd378d6742513b9c0b53a16fed309b6b6d58b72ac19c

test:
  secret_key_base: 8671e695d0985674724011132e4fc38887dee74d1b679393257a492627ad5b8625117f532d4061d1c3cbc86d45e1ddbff49a7eca01f044335d439c65514fa6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
